name: CI - Formatting

on:
  push:
    branches: ["open-source"]
  pull_request:
    branches: ["open-source"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '14'
        check-path: 'src'
